export function processData(data) {
  // const processedData = {}
  let {
    resolvedAddress: address,
    latitude,
    longitude,
    timezone,
    tzoffset,
    currentConditions: { conditions: currentCondition },
    currentConditions: { feelslike: currentFeelslike },
    currentConditions: { humidity: currentHumidity },
    currentConditions: { icon: currentIcon },
    currentConditions: { temp: currentTemperature },
    days: [
      { datetime: date0 },
      { datetime: date1 },
      { datetime: date2 },
      { datetime: date3 },
      { datetime: date4 },
      { datetime: date5 },
      { datetime: date6 },
    ],
    days: [
      { conditions: conditions0 },
      { conditions: conditions1 },
      { conditions: conditions2 },
      { conditions: conditions3 },
      { conditions: conditions4 },
      { conditions: conditions5 },
      { conditions: conditions6 },
    ],
    days: [
      { feelslike: feelslike0 },
      { feelslike: feelslike1 },
      { feelslike: feelslike2 },
      { feelslike: feelslike3 },
      { feelslike: feelslike4 },
      { feelslike: feelslike5 },
      { feelslike: feelslike6 },
    ],
    days: [
      { humidity: humidity0 },
      { humidity: humidity1 },
      { humidity: humidity2 },
      { humidity: humidity3 },
      { humidity: humidity4 },
      { humidity: humidity5 },
      { humidity: humidity6 },
    ],
    days: [
      { temp: temperature0 },
      { temp: temperature1 },
      { temp: temperature2 },
      { temp: temperature3 },
      { temp: temperature4 },
      { temp: temperature5 },
      { temp: temperature6 },
    ],
    days: [
      { icon: icon0 },
      { icon: icon1 },
      { icon: icon2 },
      { icon: icon3 },
      { icon: icon4 },
      { icon: icon5 },
      { icon: icon6 },
    ],
    days: [
      {
        hours: [
          { conditions: condition0h00 },
          { conditions: condition0h01 },
          { conditions: condition0h02 },
          { conditions: condition0h03 },
          { conditions: condition0h04 },
          { conditions: condition0h05 },
          { conditions: condition0h06 },
          { conditions: condition0h07 },
          { conditions: condition0h08 },
          { conditions: condition0h09 },
          { conditions: condition0h10 },
          { conditions: condition0h11 },
          { conditions: condition0h12 },
          { conditions: condition0h13 },
          { conditions: condition0h14 },
          { conditions: condition0h15 },
          { conditions: condition0h16 },
          { conditions: condition0h17 },
          { conditions: condition0h18 },
          { conditions: condition0h19 },
          { conditions: condition0h20 },
          { conditions: condition0h21 },
          { conditions: condition0h22 },
          { conditions: condition0h23 },
        ],
      },
      {
        hours: [
          { conditions: condition1h00 },
          { conditions: condition1h01 },
          { conditions: condition1h02 },
          { conditions: condition1h03 },
          { conditions: condition1h04 },
          { conditions: condition1h05 },
          { conditions: condition1h06 },
          { conditions: condition1h07 },
          { conditions: condition1h08 },
          { conditions: condition1h09 },
          { conditions: condition1h10 },
          { conditions: condition1h11 },
          { conditions: condition1h12 },
          { conditions: condition1h13 },
          { conditions: condition1h14 },
          { conditions: condition1h15 },
          { conditions: condition1h16 },
          { conditions: condition1h17 },
          { conditions: condition1h18 },
          { conditions: condition1h19 },
          { conditions: condition1h20 },
          { conditions: condition1h21 },
          { conditions: condition1h22 },
          { conditions: condition1h23 },
        ],
      },
      {
        hours: [
          { conditions: condition2h00 },
          { conditions: condition2h01 },
          { conditions: condition2h02 },
          { conditions: condition2h03 },
          { conditions: condition2h04 },
          { conditions: condition2h05 },
          { conditions: condition2h06 },
          { conditions: condition2h07 },
          { conditions: condition2h08 },
          { conditions: condition2h09 },
          { conditions: condition2h10 },
          { conditions: condition2h11 },
          { conditions: condition2h12 },
          { conditions: condition2h13 },
          { conditions: condition2h14 },
          { conditions: condition2h15 },
          { conditions: condition2h16 },
          { conditions: condition2h17 },
          { conditions: condition2h18 },
          { conditions: condition2h19 },
          { conditions: condition2h20 },
          { conditions: condition2h21 },
          { conditions: condition2h22 },
          { conditions: condition2h23 },
        ],
      },
    ],
    days: [
      {
        hours: [
          { feelslike0: feelslike0h00 },
          { feelslike: feelslike0h01 },
          { feelslike: feelslike0h02 },
          { feelslike: feelslike0h03 },
          { feelslike: feelslike0h04 },
          { feelslike: feelslike0h05 },
          { feelslike: feelslike0h06 },
          { feelslike: feelslike0h07 },
          { feelslike: feelslike0h08 },
          { feelslike: feelslike0h09 },
          { feelslike: feelslike0h10 },
          { feelslike: feelslike0h11 },
          { feelslike: feelslike0h12 },
          { feelslike: feelslike0h13 },
          { feelslike: feelslike0h14 },
          { feelslike: feelslike0h15 },
          { feelslike: feelslike0h16 },
          { feelslike: feelslike0h17 },
          { feelslike: feelslike0h18 },
          { feelslike: feelslike0h19 },
          { feelslike: feelslike0h20 },
          { feelslike: feelslike0h21 },
          { feelslike: feelslike0h22 },
          { feelslike: feelslike0h23 },
        ],
      },
      {
        hours: [
          { feelslike: feelslike1h00 },
          { feelslike: feelslike1h01 },
          { feelslike: feelslike1h02 },
          { feelslike: feelslike1h03 },
          { feelslike: feelslike1h04 },
          { feelslike: feelslike1h05 },
          { feelslike: feelslike1h06 },
          { feelslike: feelslike1h07 },
          { feelslike: feelslike1h08 },
          { feelslike: feelslike1h09 },
          { feelslike: feelslike1h10 },
          { feelslike: feelslike1h11 },
          { feelslike: feelslike1h12 },
          { feelslike: feelslike1h13 },
          { feelslike: feelslike1h14 },
          { feelslike: feelslike1h15 },
          { feelslike: feelslike1h16 },
          { feelslike: feelslike1h17 },
          { feelslike: feelslike1h18 },
          { feelslike: feelslike1h19 },
          { feelslike: feelslike1h20 },
          { feelslike: feelslike1h21 },
          { feelslike: feelslike1h22 },
          { feelslike: feelslike1h23 },
        ],
      },
      {
        hours: [
          { feelslike: feelslike2h00 },
          { feelslike: feelslike2h01 },
          { feelslike: feelslike2h02 },
          { feelslike: feelslike2h03 },
          { feelslike: feelslike2h04 },
          { feelslike: feelslike2h05 },
          { feelslike: feelslike2h06 },
          { feelslike: feelslike2h07 },
          { feelslike: feelslike2h08 },
          { feelslike: feelslike2h09 },
          { feelslike: feelslike2h10 },
          { feelslike: feelslike2h11 },
          { feelslike: feelslike2h12 },
          { feelslike: feelslike2h13 },
          { feelslike: feelslike2h14 },
          { feelslike: feelslike2h15 },
          { feelslike: feelslike2h16 },
          { feelslike: feelslike2h17 },
          { feelslike: feelslike2h18 },
          { feelslike: feelslike2h19 },
          { feelslike: feelslike2h20 },
          { feelslike: feelslike2h21 },
          { feelslike: feelslike2h22 },
          { feelslike: feelslike2h23 },
        ],
      },
    ],
    days: [
      {
        hours: [
          { humidity: humidity0h00 },
          { humidity: humidity0h01 },
          { humidity: humidity0h02 },
          { humidity: humidity0h03 },
          { humidity: humidity0h04 },
          { humidity: humidity0h05 },
          { humidity: humidity0h06 },
          { humidity: humidity0h07 },
          { humidity: humidity0h08 },
          { humidity: humidity0h09 },
          { humidity: humidity0h10 },
          { humidity: humidity0h11 },
          { humidity: humidity0h12 },
          { humidity: humidity0h13 },
          { humidity: humidity0h14 },
          { humidity: humidity0h15 },
          { humidity: humidity0h16 },
          { humidity: humidity0h17 },
          { humidity: humidity0h18 },
          { humidity: humidity0h19 },
          { humidity: humidity0h20 },
          { humidity: humidity0h21 },
          { humidity: humidity0h22 },
          { humidity: humidity0h23 },
        ],
      },
      {
        hours: [
          { humidity: humidity1h00 },
          { humidity: humidity1h01 },
          { humidity: humidity1h02 },
          { humidity: humidity1h03 },
          { humidity: humidity1h04 },
          { humidity: humidity1h05 },
          { humidity: humidity1h06 },
          { humidity: humidity1h07 },
          { humidity: humidity1h08 },
          { humidity: humidity1h09 },
          { humidity: humidity1h10 },
          { humidity: humidity1h11 },
          { humidity: humidity1h12 },
          { humidity: humidity1h13 },
          { humidity: humidity1h14 },
          { humidity: humidity1h15 },
          { humidity: humidity1h16 },
          { humidity: humidity1h17 },
          { humidity: humidity1h18 },
          { humidity: humidity1h19 },
          { humidity: humidity1h20 },
          { humidity: humidity1h21 },
          { humidity: humidity1h22 },
          { humidity: humidity1h23 },
        ],
      },
      {
        hours: [
          { humidity: humidity2h00 },
          { humidity: humidity2h01 },
          { humidity: humidity2h02 },
          { humidity: humidity2h03 },
          { humidity: humidity2h04 },
          { humidity: humidity2h05 },
          { humidity: humidity2h06 },
          { humidity: humidity2h07 },
          { humidity: humidity2h08 },
          { humidity: humidity2h09 },
          { humidity: humidity2h10 },
          { humidity: humidity2h11 },
          { humidity: humidity2h12 },
          { humidity: humidity2h13 },
          { humidity: humidity2h14 },
          { humidity: humidity2h15 },
          { humidity: humidity2h16 },
          { humidity: humidity2h17 },
          { humidity: humidity2h18 },
          { humidity: humidity2h19 },
          { humidity: humidity2h20 },
          { humidity: humidity2h21 },
          { humidity: humidity2h22 },
          { humidity: humidity2h23 },
        ],
      },
    ],
    days: [
      {
        hours: [
          { icon: icon0h00 },
          { icon: icon0h01 },
          { icon: icon0h02 },
          { icon: icon0h03 },
          { icon: icon0h04 },
          { icon: icon0h05 },
          { icon: icon0h06 },
          { icon: icon0h07 },
          { icon: icon0h08 },
          { icon: icon0h09 },
          { icon: icon0h10 },
          { icon: icon0h11 },
          { icon: icon0h12 },
          { icon: icon0h13 },
          { icon: icon0h14 },
          { icon: icon0h15 },
          { icon: icon0h16 },
          { icon: icon0h17 },
          { icon: icon0h18 },
          { icon: icon0h19 },
          { icon: icon0h20 },
          { icon: icon0h21 },
          { icon: icon0h22 },
          { icon: icon0h23 },
        ],
      },
      {
        hours: [
          { icon: icon1h00 },
          { icon: icon1h01 },
          { icon: icon1h02 },
          { icon: icon1h03 },
          { icon: icon1h04 },
          { icon: icon1h05 },
          { icon: icon1h06 },
          { icon: icon1h07 },
          { icon: icon1h08 },
          { icon: icon1h09 },
          { icon: icon1h10 },
          { icon: icon1h11 },
          { icon: icon1h12 },
          { icon: icon1h13 },
          { icon: icon1h14 },
          { icon: icon1h15 },
          { icon: icon1h16 },
          { icon: icon1h17 },
          { icon: icon1h18 },
          { icon: icon1h19 },
          { icon: icon1h20 },
          { icon: icon1h21 },
          { icon: icon1h22 },
          { icon: icon1h23 },
        ],
      },
      {
        hours: [
          { icon: icon2h00 },
          { icon: icon2h01 },
          { icon: icon2h02 },
          { icon: icon2h03 },
          { icon: icon2h04 },
          { icon: icon2h05 },
          { icon: icon2h06 },
          { icon: icon2h07 },
          { icon: icon2h08 },
          { icon: icon2h09 },
          { icon: icon2h10 },
          { icon: icon2h11 },
          { icon: icon2h12 },
          { icon: icon2h13 },
          { icon: icon2h14 },
          { icon: icon2h15 },
          { icon: icon2h16 },
          { icon: icon2h17 },
          { icon: icon2h18 },
          { icon: icon2h19 },
          { icon: icon2h20 },
          { icon: icon2h21 },
          { icon: icon2h22 },
          { icon: icon2h23 },
        ],
      },
    ],
    days: [
      {
        hours: [
          { temp: temperature0h00 },
          { temp: temperature0h01 },
          { temp: temperature0h02 },
          { temp: temperature0h03 },
          { temp: temperature0h04 },
          { temp: temperature0h05 },
          { temp: temperature0h06 },
          { temp: temperature0h07 },
          { temp: temperature0h08 },
          { temp: temperature0h09 },
          { temp: temperature0h10 },
          { temp: temperature0h11 },
          { temp: temperature0h12 },
          { temp: temperature0h13 },
          { temp: temperature0h14 },
          { temp: temperature0h15 },
          { temp: temperature0h16 },
          { temp: temperature0h17 },
          { temp: temperature0h18 },
          { temp: temperature0h19 },
          { temp: temperature0h20 },
          { temp: temperature0h21 },
          { temp: temperature0h22 },
          { temp: temperature0h23 },
        ],
      },
      {
        hours: [
          { temp: temperature1h00 },
          { temp: temperature1h01 },
          { temp: temperature1h02 },
          { temp: temperature1h03 },
          { temp: temperature1h04 },
          { temp: temperature1h05 },
          { temp: temperature1h06 },
          { temp: temperature1h07 },
          { temp: temperature1h08 },
          { temp: temperature1h09 },
          { temp: temperature1h10 },
          { temp: temperature1h11 },
          { temp: temperature1h12 },
          { temp: temperature1h13 },
          { temp: temperature1h14 },
          { temp: temperature1h15 },
          { temp: temperature1h16 },
          { temp: temperature1h17 },
          { temp: temperature1h18 },
          { temp: temperature1h19 },
          { temp: temperature1h20 },
          { temp: temperature1h21 },
          { temp: temperature1h22 },
          { temp: temperature1h23 },
        ],
      },
      {
        hours: [
          { temp: temperature2h00 },
          { temp: temperature2h01 },
          { temp: temperature2h02 },
          { temp: temperature2h03 },
          { temp: temperature2h04 },
          { temp: temperature2h05 },
          { temp: temperature2h06 },
          { temp: temperature2h07 },
          { temp: temperature2h08 },
          { temp: temperature2h09 },
          { temp: temperature2h10 },
          { temp: temperature2h11 },
          { temp: temperature2h12 },
          { temp: temperature2h13 },
          { temp: temperature2h14 },
          { temp: temperature2h15 },
          { temp: temperature2h16 },
          { temp: temperature2h17 },
          { temp: temperature2h18 },
          { temp: temperature2h19 },
          { temp: temperature2h20 },
          { temp: temperature2h21 },
          { temp: temperature2h22 },
          { temp: temperature2h23 },
        ],
      },
    ],
  } = data;

  return {
    address,
    latitude,
    longitude,
    timezone,
    tzoffset,
    currentCondition,
    currentFeelslike,
    currentHumidity,
    currentIcon,
    currentTemperature,
    date0,
    date1,
    date2,
    date3,
    date4,
    date5,
    date6,
    conditions0,
    conditions1,
    conditions2,
    conditions3,
    conditions4,
    conditions5,
    conditions6,
    feelslike0,
    feelslike1,
    feelslike2,
    feelslike3,
    feelslike4,
    feelslike5,
    feelslike6,
    humidity0,
    humidity1,
    humidity2,
    humidity3,
    humidity4,
    humidity5,
    humidity6,
    temperature0,
    temperature1,
    temperature2,
    temperature3,
    temperature4,
    temperature5,
    temperature6,
    icon0,
    icon1,
    icon2,
    icon3,
    icon4,
    icon5,
    icon6,
    condition0h00,
    condition0h01,
    condition0h02,
    condition0h03,
    condition0h04,
    condition0h05,
    condition0h06,
    condition0h07,
    condition0h08,
    condition0h09,
    condition0h10,
    condition0h11,
    condition0h12,
    condition0h13,
    condition0h14,
    condition0h15,
    condition0h16,
    condition0h17,
    condition0h18,
    condition0h19,
    condition0h20,
    condition0h21,
    condition0h22,
    condition0h23,
    condition1h00,
    condition1h01,
    condition1h02,
    condition1h03,
    condition1h04,
    condition1h05,
    condition1h06,
    condition1h07,
    condition1h08,
    condition1h09,
    condition1h10,
    condition1h11,
    condition1h12,
    condition1h13,
    condition1h14,
    condition1h15,
    condition1h16,
    condition1h17,
    condition1h18,
    condition1h19,
    condition1h20,
    condition1h21,
    condition1h22,
    condition1h23,
    condition2h00,
    condition2h01,
    condition2h02,
    condition2h03,
    condition2h04,
    condition2h05,
    condition2h06,
    condition2h07,
    condition2h08,
    condition2h09,
    condition2h10,
    condition2h11,
    condition2h12,
    condition2h13,
    condition2h14,
    condition2h15,
    condition2h16,
    condition2h17,
    condition2h18,
    condition2h19,
    condition2h20,
    condition2h21,
    condition2h22,
    condition2h23,
    feelslike0h00,
    feelslike0h01,
    feelslike0h02,
    feelslike0h03,
    feelslike0h04,
    feelslike0h05,
    feelslike0h06,
    feelslike0h07,
    feelslike0h08,
    feelslike0h09,
    feelslike0h10,
    feelslike0h11,
    feelslike0h12,
    feelslike0h13,
    feelslike0h14,
    feelslike0h15,
    feelslike0h16,
    feelslike0h17,
    feelslike0h18,
    feelslike0h19,
    feelslike0h20,
    feelslike0h21,
    feelslike0h22,
    feelslike0h23,
    feelslike1h00,
    feelslike1h01,
    feelslike1h02,
    feelslike1h03,
    feelslike1h04,
    feelslike1h05,
    feelslike1h06,
    feelslike1h07,
    feelslike1h08,
    feelslike1h09,
    feelslike1h10,
    feelslike1h11,
    feelslike1h12,
    feelslike1h13,
    feelslike1h14,
    feelslike1h15,
    feelslike1h16,
    feelslike1h17,
    feelslike1h18,
    feelslike1h19,
    feelslike1h20,
    feelslike1h21,
    feelslike1h22,
    feelslike1h23,
    feelslike2h00,
    feelslike2h01,
    feelslike2h02,
    feelslike2h03,
    feelslike2h04,
    feelslike2h05,
    feelslike2h06,
    feelslike2h07,
    feelslike2h08,
    feelslike2h09,
    feelslike2h10,
    feelslike2h11,
    feelslike2h12,
    feelslike2h13,
    feelslike2h14,
    feelslike2h15,
    feelslike2h16,
    feelslike2h17,
    feelslike2h18,
    feelslike2h19,
    feelslike2h20,
    feelslike2h21,
    feelslike2h22,
    feelslike2h23,
    humidity0h00,
    humidity0h01,
    humidity0h02,
    humidity0h03,
    humidity0h04,
    humidity0h05,
    humidity0h06,
    humidity0h07,
    humidity0h08,
    humidity0h09,
    humidity0h10,
    humidity0h11,
    humidity0h12,
    humidity0h13,
    humidity0h14,
    humidity0h15,
    humidity0h16,
    humidity0h17,
    humidity0h18,
    humidity0h19,
    humidity0h20,
    humidity0h21,
    humidity0h22,
    humidity0h23,
    humidity1h00,
    humidity1h01,
    humidity1h02,
    humidity1h03,
    humidity1h04,
    humidity1h05,
    humidity1h06,
    humidity1h07,
    humidity1h08,
    humidity1h09,
    humidity1h10,
    humidity1h11,
    humidity1h12,
    humidity1h13,
    humidity1h14,
    humidity1h15,
    humidity1h16,
    humidity1h17,
    humidity1h18,
    humidity1h19,
    humidity1h20,
    humidity1h21,
    humidity1h22,
    humidity1h23,
    humidity2h00,
    humidity2h01,
    humidity2h02,
    humidity2h03,
    humidity2h04,
    humidity2h05,
    humidity2h06,
    humidity2h07,
    humidity2h08,
    humidity2h09,
    humidity2h10,
    humidity2h11,
    humidity2h12,
    humidity2h13,
    humidity2h14,
    humidity2h15,
    humidity2h16,
    humidity2h17,
    humidity2h18,
    humidity2h19,
    humidity2h20,
    humidity2h21,
    humidity2h22,
    humidity2h23,
    icon0h00,
    icon0h01,
    icon0h02,
    icon0h03,
    icon0h04,
    icon0h05,
    icon0h06,
    icon0h07,
    icon0h08,
    icon0h09,
    icon0h10,
    icon0h11,
    icon0h12,
    icon0h13,
    icon0h14,
    icon0h15,
    icon0h16,
    icon0h17,
    icon0h18,
    icon0h19,
    icon0h20,
    icon0h21,
    icon0h22,
    icon0h23,
    icon1h00,
    icon1h01,
    icon1h02,
    icon1h03,
    icon1h04,
    icon1h05,
    icon1h06,
    icon1h07,
    icon1h08,
    icon1h09,
    icon1h10,
    icon1h11,
    icon1h12,
    icon1h13,
    icon1h14,
    icon1h15,
    icon1h16,
    icon1h17,
    icon1h18,
    icon1h19,
    icon1h20,
    icon1h21,
    icon1h22,
    icon1h23,
    icon2h00,
    icon2h01,
    icon2h02,
    icon2h03,
    icon2h04,
    icon2h05,
    icon2h06,
    icon2h07,
    icon2h08,
    icon2h09,
    icon2h10,
    icon2h11,
    icon2h12,
    icon2h13,
    icon2h14,
    icon2h15,
    icon2h16,
    icon2h17,
    icon2h18,
    icon2h19,
    icon2h20,
    icon2h21,
    icon2h22,
    icon2h23,
    temperature0h00,
    temperature0h01,
    temperature0h02,
    temperature0h03,
    temperature0h04,
    temperature0h05,
    temperature0h06,
    temperature0h07,
    temperature0h08,
    temperature0h09,
    temperature0h10,
    temperature0h11,
    temperature0h12,
    temperature0h13,
    temperature0h14,
    temperature0h15,
    temperature0h16,
    temperature0h17,
    temperature0h18,
    temperature0h19,
    temperature0h20,
    temperature0h21,
    temperature0h22,
    temperature0h23,
    temperature1h00,
    temperature1h01,
    temperature1h02,
    temperature1h03,
    temperature1h04,
    temperature1h05,
    temperature1h06,
    temperature1h07,
    temperature1h08,
    temperature1h09,
    temperature1h10,
    temperature1h11,
    temperature1h12,
    temperature1h13,
    temperature1h14,
    temperature1h15,
    temperature1h16,
    temperature1h17,
    temperature1h18,
    temperature1h19,
    temperature1h20,
    temperature1h21,
    temperature1h22,
    temperature1h23,
    temperature2h00,
    temperature2h01,
    temperature2h02,
    temperature2h03,
    temperature2h04,
    temperature2h05,
    temperature2h06,
    temperature2h07,
    temperature2h08,
    temperature2h09,
    temperature2h10,
    temperature2h11,
    temperature2h12,
    temperature2h13,
    temperature2h14,
    temperature2h15,
    temperature2h16,
    temperature2h17,
    temperature2h18,
    temperature2h19,
    temperature2h20,
    temperature2h21,
    temperature2h22,
    temperature2h23,
  };
}
